-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le :  lun. 08 avr. 2019 à 15:35
-- Version du serveur :  5.7.25
-- Version de PHP :  5.6.40

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `app_comm`
--

-- --------------------------------------------------------

--
-- Structure de la table `builder_block_type`
--

CREATE TABLE `builder_block_type` (
  `id` int(10) UNSIGNED NOT NULL,
  `id_group` int(11) DEFAULT NULL,
  `theme` int(11) NOT NULL,
  `nom` varchar(100) DEFAULT NULL,
  `builder_block_html` text,
  `affichage` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `builder_block_type`
--

INSERT INTO `builder_block_type` (`id`, `id_group`, `theme`, `nom`, `builder_block_html`, `affichage`) VALUES
(1, 1, 1, 'Top', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"1\"><input type=\"hidden\" name=\"nom\" value=\"Top\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/top.png\" alt=\"\"><p>Top</p></div>', 0),
(2, 1, 1, 'Header', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"2\"><input type=\"hidden\" name=\"nom\" value=\"Header\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/header.png\" alt=\"\"><p>Header</p></div>', 0),
(3, 1, 1, 'Headline', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"3\"><input type=\"hidden\" name=\"nom\" value=\"Headline\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre de la newsletter\"><input class=\"block_input\" type=\"hidden\" name=\"block_input[]\" value=\"3\" data-col=\"1\" data-label=\"Numero de la newsletter\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Date de la newsletter\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/headline.png\" alt=\"\"><p>Headline</p></div>', 1),
(4, 1, 1, 'Image', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"4\"><input type=\"hidden\" name=\"nom\" value=\"Image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"700x450\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/image.png\" alt=\"\"><p>Image</p></div>', 1),
(5, 1, 1, 'Titre', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"5\"><input type=\"hidden\" name=\"nom\" value=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/titre.png\" alt=\"\"><p>Titre</p></div>', 1),
(6, 1, 1, 'Paragraphe', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"6\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre du bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien du bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/paragraphe.png\" alt=\"\"><p>Paragraphe</p></div>', 1),
(7, 1, 1, 'Séparation', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"7\"><input type=\"hidden\" name=\"nom\" value=\"Séparation\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/divider.png\" alt=\"\"><p>Séparation</p></div>', 1),
(8, 1, 1, 'Signature', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"8\"><input type=\"hidden\" name=\"nom\" value=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Nom et Prénom\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Fonction\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Mail\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Téléphone\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/signature.png\" alt=\"\"><p>Signature</p></div>', 1),
(9, 1, 1, '2 colonnes', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"9\"><input type=\"hidden\" name=\"nom\" value=\"2 colonnes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 1\" data-crop=\"330x250\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"2\" data-label=\"Image colonne 2\" data-crop=\"330x250\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien image colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"2\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien bouton colonne 2\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/2_col.png\" alt=\"\"><p>2 colonnes</p></div>', 1),
(10, 1, 1, '3 colonnes', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"10\"><input type=\"hidden\" name=\"nom\" value=\"3 colonnes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 1\" data-crop=\"210x250\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"2\" data-label=\"Image colonne 2\" data-crop=\"210x250\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien image colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"2\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"3\" data-label=\"Image colonne 3\" data-crop=\"210x250\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Lien image colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Titre colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"3\" data-label=\"Texte colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Titre bouton colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Lien bouton colonne 3\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/3_col.png\" alt=\"\"><p>3 colonnes</p></div>', 1),
(11, 1, 1, 'Article', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"11\"><input type=\"hidden\" name=\"nom\" value=\"Article\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"450x500\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/article.png\" alt=\"\"><p>Article</p></div>', 1),
(12, 1, 1, 'Testimonial', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"12\"><input type=\"hidden\" name=\"nom\" value=\"Testimonial\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"95x96\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Nom et Prénom\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Fonction\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/testimonial.png\" alt=\"\"><p>Testimonial</p></div>', 1),
(13, 1, 1, 'Appel à action A', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"13\"><input type=\"hidden\" name=\"nom\" value=\"Appel à action A\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/callout_alpha.png\" alt=\"\"><p>Appel à action A</p></div>', 1),
(14, 1, 1, 'Appel à action B', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"14\"><input type=\"hidden\" name=\"nom\" value=\"Appel à action B\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Mention\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/callout_beta.png\" alt=\"\"><p>Appel à action B</p></div>', 1),
(15, 1, 1, 'Post', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"15\"><input type=\"hidden\" name=\"nom\" value=\"Post\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 2\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/blog_post.png\" alt=\"\"><p>Post</p></div>', 1),
(16, 1, 1, 'Éditor', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"16\"><input type=\"hidden\" name=\"nom\" value=\"Édito\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"159x185\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Nom et Prénom\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Fonction\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/editor.png\" alt=\"\"><p>Éditor</p></div>', 1),
(17, 1, 1, 'Paragraphe jaune', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"17\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe jaune\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_jaune.png\" alt=\"\"><p>Paragraphe jaune</p></div>', 1),
(18, 1, 1, 'Paragraphe bleu gris', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"18\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe bleu gris\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_bleu_gris.png\" alt=\"\"><p>Paragraphe bleu gris</p></div>', 1),
(19, 1, 1, 'Paragraphe violet', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"19\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe violet\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_violette.png\" alt=\"\"><p>Paragraphe violet</p></div>', 1),
(20, 1, 1, 'Paragraphe bleu', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"20\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe bleu\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_bleu.png\" alt=\"\"><p>Paragraphe bleu</p></div>', 1),
(21, 1, 1, 'Paragraphe orange', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"21\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe orange\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_orange.png\" alt=\"\"><p>Paragraphe orange</p></div>', 1),
(22, 1, 1, 'Paragraphe turquoise', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"22\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe turquoise\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/thematique_turquoise.png\" alt=\"\"><p>Paragraphe turquoise</p></div>', 1),
(23, 1, 1, 'Mise en avant A', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"23\"><input type=\"hidden\" name=\"nom\" value=\"Mise en avant A\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Date\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/highlight_alpha.png\" alt=\"\"><p>Mise en avant A</p></div>', 1),
(24, 1, 1, 'Mise en avant B', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"24\"><input type=\"hidden\" name=\"nom\" value=\"Mise en avant B\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Date\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Salle\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Adresse\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/highlight_beta.png\" alt=\"\"><p>Mise en avant B</p></div>', 1),
(25, 1, 1, 'Footer', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"25\"><input type=\"hidden\" name=\"nom\" value=\"Footer\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/footer.png\" alt=\"\"><p>Footer</p></div>', 0),
(26, 1, 1, 'Footer bar', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"26\"><input type=\"hidden\" name=\"nom\" value=\"Footer bar\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/footer_bar.png\" alt=\"\"><p>Footer bar</p></div>', 0),
(27, 1, 1, 'Bottom', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"27\"><input type=\"hidden\" name=\"nom\" value=\"Bottom\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/seddre/template_images/bottom.png\" alt=\"\"><p>Bottom</p></div>', 0),
(28, 2, 2, 'Top', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"28\"><input type=\"hidden\" name=\"nom\" value=\"Top\"><img class=\"smallblockIcon\" src=\"/mediatheque/newsletter/steva/template_images/top.png\" alt=\"\"><p>Top</p></div>', 0),
(29, 2, 2, 'Headline', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"29\"><input type=\"hidden\" name=\"nom\" value=\"Headline\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre de la newsletter\"><img class=\"smallblockIcon\" src=\"/mediatheque/newsletter/steva/template_images/headline.png\" alt=\"\"><p>Headline</p></div>', 0),
(30, 2, 2, 'Image', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"30\"><input type=\"hidden\" name=\"nom\" value=\"Image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"700x450\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/image.png\" alt=\"\"><p>Image</p></div>', 1),
(31, 2, 2, 'Titre', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"31\"><input type=\"hidden\" name=\"nom\" value=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre.png\" alt=\"\"><p>Titre</p></div>', 1),
(32, 2, 2, 'Paragraphe', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"32\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe\"><input type=\"hidden\" class=\"block_input\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input type=\"hidden\" class=\"block_input\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre\"><input type=\"hidden\" class=\"block_input\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/paragraphe.png\" alt=\"\"><p>Paragraphe</p></div>', 1),
(33, 2, 2, 'Séparation ', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"33\"><input type=\"hidden\" name=\"nom\" value=\"Séparation\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/separation.png\" alt=\"\"><p>Séparation</p></div>', 1),
(34, 2, 2, '2 grandes colonnes bleu et image à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"34\"><input type=\"hidden\" name=\"nom\" value=\"2 grandes colonnes bleu et image à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x400\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_grandes_cols_bleu_image_gauche.png\" alt=\"\"><p>2 colonnes bleu et image à gauche</p></div>', 1),
(35, 2, 2, '2 grandes colonnes bleu et image à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"35\"><input type=\"hidden\" name=\"nom\" value=\"2 grandes colonnes bleu et image à droite\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x400\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_grandes_cols_bleu_image_droite.png\" alt=\"\"><p>2 colonnes bleu et image à droite</p></div>', 1),
(36, 2, 2, '2 grandes colonnes blanches et image à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"36\"><input type=\"hidden\" name=\"nom\" value=\"2 grandes colonnes blanches et image à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_grandes_cols_blanches_image_gauche.png\" alt=\"\"><p>2 colonnes blanches et image à gauche</p></div>', 1),
(37, 2, 2, '2 grandes colonnes blanches et image à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"37\"><input type=\"hidden\" name=\"nom\" value=\"2 grandes colonnes blanches et image à droite\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_grandes_cols_blanches_image_droite.png\" alt=\"\"><p>2 colonnes blanches et image à droite</p></div>', 1),
(38, 2, 2, '2 petites colonnes bleu et image à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"38\"><input type=\"hidden\" name=\"nom\" value=\"2 petites colonnes bleu et image à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"averageBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_petites_cols_bleu_image_gauche.png\" alt=\"\"><p>2 petites colonnes bleu et image à gauche</p></div>', 1),
(39, 2, 2, '2 petites colonnes bleu et image à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"39\"><input type=\"hidden\" name=\"nom\" value=\"2 petites colonnes bleu et image à droite\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"averageBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_petites_cols_bleu_image_droite.png\" alt=\"\"><p>2 petites colonnes bleu et image à droite</p></div>', 1),
(40, 2, 2, '2 petites colonnes blanches et image à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"40\"><input type=\"hidden\" name=\"nom\" value=\"2 petites colonnes blanches et image à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"averageBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_petites_cols_blanches_image_gauche.png\" alt=\"\"><p>2 petites colonnes blanches et image à gauche</p></div>', 1),
(41, 2, 2, '2 petites colonnes blanches et image à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"41\"><input type=\"hidden\" name=\"nom\" value=\"2 petites colonnes blanches et image à droite\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"400x262\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"averageBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_petites_cols_blanches_image_droite.png\" alt=\"\"><p>2 petites colonnes blanches et image à droite</p></div>', 1),
(42, 2, 2, '2 colonnes images et textes', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"42\"><input type=\"hidden\" name=\"nom\" value=\"2 colonnes images et textes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image collonne 1\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image collonne 2\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 2\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/2_cols.png\" alt=\"\"><p>2 colonnes images et texte</p></div>', 1),
(43, 2, 2, '3 colonnes images et texte', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"43\"><input type=\"hidden\" name=\"nom\" value=\"3 colonnes images et textes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 1\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 2\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 3\" data-crop=\"216X126\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 3\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/3_cols.png\" alt=\"\"><p>3 colonnes images et texte</p></div>', 1),
(44, 2, 2, '3 colonnes logos et texte', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"44\"><input type=\"hidden\" name=\"nom\" value=\"3 colonnes logos et texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image collonne 1\" data-crop=\"216X130\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image collonne 2\" data-crop=\"216X130\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image collonne 3\" data-crop=\"216X130\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 3\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/3_cols_logos.png\" alt=\"\"><p>3 colonnes logos et texte</p></div>', 1),
(45, 2, 2, 'Titre et 2 images', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"45\"><input type=\"hidden\" name=\"nom\" value=\"Titre et 2 images\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"348x196\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image 2\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre_2_images.png\" alt=\"\"><p>Titre et 2 images</p></div>', 1),
(46, 2, 2, 'Testimonial', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"46\"><input type=\"hidden\" name=\"nom\" value=\"Testimonial\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_select[]\" value=\"4\" data-col=\"1\" data-label=\"Réseaux social\" data-select=\"Facebook,Instagram,Twitter,Linkedin\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/testimonial.png\" alt=\"\"><p>Testimonial</p></div>', 1),
(47, 2, 2, 'Nos publications de la semaine', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"47\"><input type=\"hidden\" name=\"nom\" value=\"Nos publications de la semaine\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre1.png\" alt=\"\"><p>Nos publications de la semaine</p></div>', 1),
(48, 2, 2, 'La vie dans nos Villa Beausoleil', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"48\"><input type=\"hidden\" name=\"nom\" value=\"La vie dans nos Villa Beausoleil\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre2.png\" alt=\"\"><p>La vie dans nos Villa Beausoleil</p></div>', 1),
(49, 2, 2, 'L\'actualité de notre secteur cette semaine !', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"49\"><input type=\"hidden\" name=\"nom\" value=\"L\\\'actualité de notre secteur cette semaine !\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre3.png\" alt=\"\"><p>L\\\'actualité de notre secteur cette semaine !</p></div>', 1),
(50, 2, 2, 'On parle de nous', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"50\"><input type=\"hidden\" name=\"nom\" value=\"On parle de nous\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/titre4.png\" alt=\"\"><p>On parle de nous</p></div>', 1),
(51, 2, 2, 'Footer', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"51\"><input type=\"hidden\" name=\"nom\" value=\"Footer\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/footer.png\" alt=\"\"><p>Footer</p></div>', 0),
(52, 2, 2, 'Footer bar', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"52\"><input type=\"hidden\" name=\"nom\" value=\"Footer bar\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/footer_bar.png\" alt=\"\"><p>Footer bar</p></div>', 0),
(53, 2, 2, 'Bottom', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"53\"><input type=\"hidden\" name=\"nom\" value=\"Bottom\"><img class=\"smallBlockIcon\" src=\"/mediatheque/newsletter/steva/template_images/bottom.png\" alt=\"\"><p>Bottom</p></div>', 0),
(54, 3, 3, 'Top Header', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"54\"><input type=\"hidden\" name=\"nom\" value=\"Top Header\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/topheader.png\" alt=\"\"><p>Top Header</p></div>', 0),
(55, 3, 3, 'Image header famille', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"55\"><input type=\"hidden\" name=\"nom\" value=\"Image header famille\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/image_header_famille.png\" alt=\"\"><p>Image header famille</p></div>', 1),
(56, 3, 3, 'Mot du chef de villa et photo à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"56\"><input type=\"hidden\" name=\"nom\" value=\"Mot du chef de villa et photo à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"450x530\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/mot_du_chef.png\" alt=\"\"><p>Mot du chef de villa et photo à gauche</p></div>', 1);
INSERT INTO `builder_block_type` (`id`, `id_group`, `theme`, `nom`, `builder_block_html`, `affichage`) VALUES
(57, 3, 3, 'Zoom sur l\'activité et photo à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"57\"><input type=\"hidden\" name=\"nom\" value=\"Zoom sur l\\\'activité du mois\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"450x530\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/zoom_activites.png\" alt=\"\"><p>Zoom sur l\\\'activité et photo à droite</p></div>', 1),
(58, 3, 3, 'Titre', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"58\"><input type=\"hidden\" name=\"nom\" value=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/titre.png\" alt=\"\"><p>Titre</p></div>', 1),
(59, 3, 3, 'Testimonial', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"59\"><input type=\"hidden\" name=\"nom\" value=\"Testimonial\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/testimonial.png\" alt=\"\"><p>Testimonial</p></div>', 1),
(60, 3, 3, 'Image', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"60\"><input type=\"hidden\" name=\"nom\" value=\"Image\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"900x343\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/image.png\" alt=\"\"><p>Image</p></div>', 1),
(61, 3, 3, 'Section jaune', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"61\"><input type=\"hidden\" name=\"nom\" value=\"Section jaune\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/section_jaune.png\" alt=\"\"><p>Section jaune</p></div>', 1),
(62, 3, 3, 'Section rose', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"62\"><input type=\"hidden\" name=\"nom\" value=\"Section rose\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/section_rose.png\" alt=\"\"><p>Section rose</p></div>', 1),
(63, 3, 3, 'Paragraphe', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"63\"><input type=\"hidden\" name=\"nom\" value=\"Paragraphe\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton 3\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/paragraphe.png\" alt=\"\"><p>Paragraphe</p></div>', 1),
(64, 3, 3, '2 colonnes', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"64\"><input type=\"hidden\" name=\"nom\" value=\"2 colonnes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 1\" data-crop=\"345x220\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien Facebook colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"2\" data-label=\"Image colonne 2\" data-crop=\"345x220\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien Facebook colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Sous-titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"2\" data-label=\"Texte colonne 2\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/2colonnes.png\" alt=\"\"><p>2 colonnes</p></div>', 1),
(65, 3, 3, '3 colonnes', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"65\"><input type=\"hidden\" name=\"nom\" value=\"3 colonnes\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image colonne 1\" data-crop=\"210x140\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien image colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton colonne 1\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"2\" data-label=\"Image colonne 2\" data-crop=\"210x140\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien image colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"2\" data-label=\"Texte colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Titre bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"2\" data-label=\"Lien bouton colonne 2\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"3\" data-label=\"Image colonne 3\" data-crop=\"210x140\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Lien image colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Titre colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"3\" data-label=\"Texte colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Titre bouton colonne 3\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"3\" data-label=\"Lien bouton colonne 3\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/3colonnes.png\" alt=\"\"><p>3 colonnes</p></div>', 1),
(66, 3, 3, 'Bottom Footer', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"66\"><input type=\"hidden\" name=\"nom\" value=\"Bottom Footer\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/bottom_footer.png\" alt=\"\"><p>Bottom Footer</p></div>', 0),
(67, 3, 3, 'Mot du chef de villa et photo à droite', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"67\"><input type=\"hidden\" name=\"nom\" value=\"Mot du chef de villa et photo à droite\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"450x530\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Signature\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/mot_du_chef_photo_droite.png\" alt=\"\"><p>Mot du chef de villa et photo à droite</p></div>', 1),
(68, 3, 3, 'Zoom sur l\'activité et photo à gauche', '<div class=\"col-xs-2 newBlock\"><input type=\"hidden\" name=\"id_block_html\" value=\"68\"><input type=\"hidden\" name=\"nom\" value=\"Zoom sur l\\\'activité et photo à gauche\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_image[]\" value=\"1\" data-col=\"1\" data-label=\"Image\" data-crop=\"450x530\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_summernote[]\" value=\"2\" data-col=\"1\" data-label=\"Texte\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Titre bouton\"><input class=\"block_input\" type=\"hidden\" name=\"block_input_texte[]\" value=\"3\" data-col=\"1\" data-label=\"Lien bouton\"><img class=\"bigBlockIcon\" src=\"/mediatheque/newsletter/beausoleil/template_images/zoom_activites_photo_gauche.png\" alt=\"\"><p>Zoom sur l\\\'activité et photo à gauche</p></div>', 1);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `builder_block_type`
--
ALTER TABLE `builder_block_type`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `builder_block_type`
--
ALTER TABLE `builder_block_type`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=69;
